name: Editor extension

on:
  push:
    branches: [ "main" ]
    paths:
      - 'editors/**'
      - 'scripts/check_editor.sh'
      - '.github/workflows/editor.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'editors/**'
      - 'scripts/check_editor.sh'
      - '.github/workflows/editor.yml'
  workflow_dispatch:

jobs:
  check-extension:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: editors/vscode/package-lock.json

    - name: Run Editor Check
      run: bash scripts/check_editor.sh
